PROGS = 0-circular-example.c 1-circular-example32.c

# if you want to use your libpi
LPI = ../staff-objs/libpi.a

# automatically run the code
RUN = 1

# if you need to override the install
BOOTLOADER = my-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
