# this is the makefile template we use --- a bunch of stuff
# happens in the included makefile.  we will simplify, but
# for the moment, time-pressure.

LIB = libtrace.a

# the driver programs: these all must have a notmain.

# CFLAGS = -I..

# shared code linked with all driver programs.
SRC := trace-notmain.c  trace-simple.c

include $(CS140E_2023_PATH)/libpi/mk/Makefile.lib.template
