include common.mk

CFLAGS = -O -Wall

main: main.o a.o b.o c.o 
	$(CC) a.o b.o c.o main.o -o main

a.o: a.c header.h
	# print out all the special variables when compiling a.o
	# $$@ = $@
	# $$< = $<
	# $$^ = $^
	# $$* = $*
	$(CC) $(CFLAGS) -c a.c -o a.o
b.o: b.c header.h
	$(CC) -c b.c -o b.o
c.o: c.c header.h
	$(CC) -c c.c -o c.o
main.o: main.c header.h
	$(CC) -c main.c -o main.o
