# you can modify this file: we won't be touching it the rest of the quarter.

# you can override these if you want.
CC ?= gcc

# the list of sources to compile --- can list them out too, but this is easy.
SOURCES := $(wildcard ./*.c)

# define any flags you want to pass to CC
CFLAGS = -g -Og -Wall -Wno-unused-function -Werror -Wno-unused-variable

# methods used to make everything.
include staff-rules.mk
