# this is the makefile template we use --- a bunch of stuff
# happens in the included makefile.  we will simplify, but
# for the moment, time-pressure.

# the driver program.
TEST_SRC := hello.c

# the code that everyone depends on.
# SUPPORT_OBJS := mbox.o

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

# uncomment if you want it to automatically run.
RUN=1

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
