# to start with use our objects.
# for checkoff this should be 0
PROGS = 1-stack-dir.c
PROGS = 2-where-push.c
PROGS = 3-push-order.c
PROGS = 4-callee.c
PROGS = $(wildcard ./[12345]*.c)

COMMON_SRC = asm-checks.S

# uncomment if you want it to automatically run.
RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
