# need the makefile to give an error if this doesn't exist
PROGS := 0-syscall.c 1-syscall.c
COMMON_SRC := syscall-asm.S  interrupts-c.c	interrupts-asm.S

# uncomment if you want it to automatically run.
# RUN=1

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = pi-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
