PROGS = 2-logic-analyzer.c
STAFF_OBJS = staff-sw-uart.o

# if you want to use your libpi
LPI = ../staff-objs/libpi.a

# automatically run the code
RUN = 1

# if you need to override the install
BOOTLOADER = my-install

include $(CS140E_2023_PATH)/libpi/mk/Makefile.template
